{
 "title": "Celestia Validator Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "chain",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "prometheus", "label": "Prometheus", "query": { "query": "label_values(prometheus)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{name='$name'},instance)"
    }
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env'},name)"
    }
   },
   {
    "name": "env",
    "label": "surroundings",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Celestia Validator Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "Height of the network",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Validator Voting Power",
   "type": "stat",
   "description": "Validator Voting Power",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "description": "Nr. of online validators",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "description": "Number of unconfirmed transactions",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Failed Tx",
   "type": "stat",
   "description": "Failed Tx",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_failed_txs" }
   ]
  },
  {
   "title": "Validators Missing",
   "type": "stat",
   "description": "Number of validators with missing signatures",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine",
   "type": "stat",
   "description": "Total voting power of the Byzantine validators",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "description": "Mempool size",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Total Bonded Tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "% of (Missing+Byzantine)",
   "type": "stat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power + tendermint_consensus_missing_validators_power) / tendermint_consensus_validators_power) * 100"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Voting Power of Missing",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power"
    }
   ]
  },
  {
   "title": "Block Size (KBytes)",
   "type": "stat",
   "description": "Block size in KBytes",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes/1024"
    }
   ]
  },
  {
   "title": "Byzantine Validators",
   "type": "stat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators"
    }
   ]
  },
  {
   "title": "Block Time (s)",
   "type": "stat",
   "description": "Block Time",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum/tendermint_consensus_block_interval_seconds_count"
    }
   ]
  },
  {
   "title": "Bridge Local Height",
   "type": "stat",
   "description": "Local Height of the Bridge Node",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bridge_local_height{}" }
   ]
  },
  {
   "title": "Bridge Network Height",
   "type": "stat",
   "description": "Network Height seen by the Bridge Node",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bridge_network_height{}" }
   ]
  },
  {
   "title": "Status Bridge Node",
   "type": "stat",
   "description": "Status of the bridge node",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bridge_network_height{}-bridge_local_height{}"
    }
   ]
  },
  {
   "title": "Validator Detailed Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Validator Voting Power",
     "type": "graph",
     "description": "Validator voting power over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "AXL" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_validator_power",
       "legendFormat": "chain_id:{{chain_id}}/val_address:{{validator_address}}"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "graph",
     "description": "Nr. of connected peers over time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Nr. peers" }
     ],
     "targets": [
      { "expr": "tendermint_p2p_peers", "legendFormat": "chain_id:{{chain_id}}" }
     ]
    },
    {
     "title": "Block Size (KBytes)",
     "type": "graph",
     "description": "Block size in bytes over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "KBytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_block_size_bytes/1024",
       "legendFormat": "chain_id:{{chain_id}}"
      }
     ]
    },
    {
     "title": "Tx",
     "type": "graph",
     "description": "Transactions over time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Nr. Tx" }
     ],
     "targets": [
      { "expr": "tendermint_consensus_num_txs", "legendFormat": "chain_id:{{chain_id}}" }
     ]
    }
   ]
  },
  {
   "title": "Hardware Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime CT",
     "type": "stat",
     "description": "Core node uptime",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(time() - node_boot_time_seconds)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "Validator System Health",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
       "legendFormat": "CPU"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "RAM"
      },
      {
       "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
       "legendFormat": "SWAP"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{device=\"/dev/sda2\"} *100 / node_filesystem_size_bytes{device=\"/dev/sda2\"})",
       "legendFormat": "Disk"
      },
      {
       "expr": "100 - (node_filesystem_free_bytes{device=\"/dev/sda1\"} *100 / node_filesystem_size_bytes{device=\"/dev/sda1\"})",
       "legendFormat": "Boot"
      }
     ]
    },
    {
     "title": "Currently open file descriptor",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Free space for each partition",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "node_memory_SwapTotal_bytes{}" }
     ]
    },
    {
     "title": "Validator Avg. System Load",
     "type": "graph",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}*100",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}*100",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}*100",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "CPU usage, disk I/O operations per second take time（%）",
     "type": "graph",
     "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
     "gridPos": { "h": 11, "w": 11, "x": 13, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
       "legendFormat": "System"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
       "legendFormat": "User"
      },
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_% of I/O operations per second"
      },
      {
       "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
       "legendFormat": "Iowait"
      }
     ]
    },
    {
     "title": "Disk read and write rate（IOPS）",
     "type": "graph",
     "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "iops", "label": "Read (-) / write（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk read and write capacity",
     "type": "graph",
     "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "Bps", "label": "Read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk IO read and write time",
     "type": "graph",
     "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "s", "label": "Read (-) / write (+) " }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_write"
      },
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_weighted"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes", "label": "Upload (-) / Download（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8",
       "legendFormat": "{{device}}_in received"
      },
      {
       "expr": "-(irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[5m])*8)",
       "legendFormat": "{{device}}_out sent"
      }
     ]
    },
    {
     "title": "TCP Connection situation",
     "type": "graph",
     "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "ESTABLISHED"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
       "legendFormat": "TCP_inuse"
      }
     ]
    }
   ]
  }
 ]
}